### ISSUE TITLE
pme build broken

### ISSUE THREAD

**Issue by pdsouza** [maruos/android_device_htc_pme#1]
The pme build on `maru-0.7` currently fails with the error:

```
external/ant-wireless/ant_native/Android.mk: error: "antradio_app (EXECUTABLES android-arm64) missing libantradio (SHARED_LIBRARIES android-arm64)" 
```

**Comment by pintaf** [comment]
ANT+ seems an old technology that was used by last HTC phone 10 years ago (HTC Desire Eye).
I believe this ANT radio thing went from ports to ports to the HTC10. Fagyi, main contributor also removed this for LOS17.

The issue probably came because LOS removed support for this technology in their trees.

**Comment by pdsouza** [comment]
Thanks for the info @pintaf! Great to see you back here.

**Comment by pintaf** [comment]
Happy to back as well. I hope we can relaunch this project !
So the actual issue was that we missed the proprietary blobs.
`<project name="pintaf/proprietary_vendor_htc" path="vendor/htc" remote="github" revision="lineage-16.0" />`

I can feel it's been more than two years I haven't build android 😂.
